name: Issue event Workflow
on:
  issues:
    types: [ opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned ]
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
    - name: What event
      run: echo "${{ toJSON(github) }}"
